#name: Simulate Default Branch Push

#on:
#  push:

jobs:
  test-default-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "This workflow is simulating $default-branch behavior by triggering on 'main' branch."
